openapi: 3.0.3
info:
  title: Cdk Example API
  description: example AWS Python Lambda application deployed with CDK
  version: 0.1.0
servers:
  - url: http://127.0.0.1:8080
  - url: https://s0o1bq1ap7.execute-api.eu-west-1.amazonaws.com/prod

paths:
  /hello:
    get:
      operationId: webapp_stack_2022.api.hello_world
      responses:
        200:
          description: say hello
  /info:
    get:
      operationId: webapp_stack_2022.common.application_factory.info
      responses:
        200:
          description: return the application information
